# Generated by Django 3.0.1 on 2021-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0006_auto_20200406_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('source_ip', models.CharField(max_length=200)),
                ('dest_port', models.CharField(max_length=200)),
                ('conn_protocol', models.CharField(max_length=200)),
                ('conn_flag', models.CharField(max_length=200)),
                ('acl_id', models.CharField(max_length=200)),
                ('acl_sequence', models.IntegerField(max_length=12)),
                ('status', models.CharField(max_length=200)),
                ('num_accumulated_attack', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='auto_mitigate',
            field=models.BooleanField(default=False),
        ),
    ]
