# Generated by Django 3.1.6 on 2021-03-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0008_auto_20210303_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('num_accumulated_attack', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='attacklog',
            name='num_accumulated_attack',
        ),
        migrations.AddField(
            model_name='device',
            name='default_acl_id',
            field=models.CharField(default=False, max_length=128),
        ),
        migrations.CreateModel(
            name='AccessControlID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl_id', models.CharField(max_length=128)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netauto.device')),
            ],
        ),
    ]
