# Generated by Django 3.1.6 on 2021-03-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0009_auto_20210309_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacklog',
            name='dest_port',
        ),
        migrations.AddField(
            model_name='attacklog',
            name='dst_ip',
            field=models.CharField(default='any', max_length=200, verbose_name='Destination IP address'),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='dst_port',
            field=models.CharField(default=None, max_length=200, verbose_name='Destination port'),
        ),
        migrations.AlterField(
            model_name='accesscontrolid',
            name='acl_id',
            field=models.CharField(max_length=128, verbose_name='Access Control List ID'),
        ),
        migrations.AlterField(
            model_name='accesscontrolid',
            name='hostname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netauto.device', verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='acl_id',
            field=models.CharField(max_length=200, verbose_name='ACL ID'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='acl_sequence',
            field=models.IntegerField(verbose_name='ACL Sequence'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='conn_flag',
            field=models.CharField(max_length=200, verbose_name='Connection flag'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='conn_protocol',
            field=models.CharField(max_length=200, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='source_ip',
            field=models.CharField(max_length=200, verbose_name='Source IP address'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='device',
            name='auto_mitigate',
            field=models.BooleanField(default=False, verbose_name='Auto-mitigate'),
        ),
        migrations.AlterField(
            model_name='device',
            name='default_acl_id',
            field=models.CharField(default='nil', max_length=128, verbose_name='Default ACL ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=200, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=200, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
