# Generated by Django 3.1.6 on 2021-03-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0010_auto_20210312_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacklog',
            name='acl_id',
        ),
        migrations.RemoveField(
            model_name='attacklog',
            name='acl_sequence',
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='conn_flag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Connection flag'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='conn_protocol',
            field=models.CharField(blank=True, max_length=200, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='dst_port',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Destination port'),
        ),
    ]
